/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PromotionLifecycleRouteImport } from './routes/promotion.lifecycle'
import { Route as LabPlazaRouteImport } from './routes/lab.plaza'
import { Route as DemoOnlineRouteImport } from './routes/demo.online'
import { Route as AtlasOverviewRouteImport } from './routes/atlas.overview'
import { Route as AtlasDemandsRouteImport } from './routes/atlas.demands'
import { Route as LabPlazaIdRouteImport } from './routes/lab.plaza.$id'
import { Route as LabDataTwinsRouteImport } from './routes/lab.data.twins'
import { Route as LabDataModelsRouteImport } from './routes/lab.data.models'
import { Route as LabDataDatasetsRouteImport } from './routes/lab.data.datasets'
import { Route as LabCapabilityPlatformsRouteImport } from './routes/lab.capability.platforms'
import { Route as LabCapabilityHardwareRouteImport } from './routes/lab.capability.hardware'
import { Route as LabCapabilityExperienceRouteImport } from './routes/lab.capability.experience'
import { Route as LabCapabilityComponentsRouteImport } from './routes/lab.capability.components'
import { Route as LabCapabilityAiTwinRouteImport } from './routes/lab.capability.ai-twin'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PromotionLifecycleRoute = PromotionLifecycleRouteImport.update({
  id: '/promotion/lifecycle',
  path: '/promotion/lifecycle',
  getParentRoute: () => rootRouteImport,
} as any)
const LabPlazaRoute = LabPlazaRouteImport.update({
  id: '/lab/plaza',
  path: '/lab/plaza',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoOnlineRoute = DemoOnlineRouteImport.update({
  id: '/demo/online',
  path: '/demo/online',
  getParentRoute: () => rootRouteImport,
} as any)
const AtlasOverviewRoute = AtlasOverviewRouteImport.update({
  id: '/atlas/overview',
  path: '/atlas/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const AtlasDemandsRoute = AtlasDemandsRouteImport.update({
  id: '/atlas/demands',
  path: '/atlas/demands',
  getParentRoute: () => rootRouteImport,
} as any)
const LabPlazaIdRoute = LabPlazaIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => LabPlazaRoute,
} as any)
const LabDataTwinsRoute = LabDataTwinsRouteImport.update({
  id: '/lab/data/twins',
  path: '/lab/data/twins',
  getParentRoute: () => rootRouteImport,
} as any)
const LabDataModelsRoute = LabDataModelsRouteImport.update({
  id: '/lab/data/models',
  path: '/lab/data/models',
  getParentRoute: () => rootRouteImport,
} as any)
const LabDataDatasetsRoute = LabDataDatasetsRouteImport.update({
  id: '/lab/data/datasets',
  path: '/lab/data/datasets',
  getParentRoute: () => rootRouteImport,
} as any)
const LabCapabilityPlatformsRoute = LabCapabilityPlatformsRouteImport.update({
  id: '/lab/capability/platforms',
  path: '/lab/capability/platforms',
  getParentRoute: () => rootRouteImport,
} as any)
const LabCapabilityHardwareRoute = LabCapabilityHardwareRouteImport.update({
  id: '/lab/capability/hardware',
  path: '/lab/capability/hardware',
  getParentRoute: () => rootRouteImport,
} as any)
const LabCapabilityExperienceRoute = LabCapabilityExperienceRouteImport.update({
  id: '/lab/capability/experience',
  path: '/lab/capability/experience',
  getParentRoute: () => rootRouteImport,
} as any)
const LabCapabilityComponentsRoute = LabCapabilityComponentsRouteImport.update({
  id: '/lab/capability/components',
  path: '/lab/capability/components',
  getParentRoute: () => rootRouteImport,
} as any)
const LabCapabilityAiTwinRoute = LabCapabilityAiTwinRouteImport.update({
  id: '/lab/capability/ai-twin',
  path: '/lab/capability/ai-twin',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/atlas/demands': typeof AtlasDemandsRoute
  '/atlas/overview': typeof AtlasOverviewRoute
  '/demo/online': typeof DemoOnlineRoute
  '/lab/plaza': typeof LabPlazaRouteWithChildren
  '/promotion/lifecycle': typeof PromotionLifecycleRoute
  '/lab/capability/ai-twin': typeof LabCapabilityAiTwinRoute
  '/lab/capability/components': typeof LabCapabilityComponentsRoute
  '/lab/capability/experience': typeof LabCapabilityExperienceRoute
  '/lab/capability/hardware': typeof LabCapabilityHardwareRoute
  '/lab/capability/platforms': typeof LabCapabilityPlatformsRoute
  '/lab/data/datasets': typeof LabDataDatasetsRoute
  '/lab/data/models': typeof LabDataModelsRoute
  '/lab/data/twins': typeof LabDataTwinsRoute
  '/lab/plaza/$id': typeof LabPlazaIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/atlas/demands': typeof AtlasDemandsRoute
  '/atlas/overview': typeof AtlasOverviewRoute
  '/demo/online': typeof DemoOnlineRoute
  '/lab/plaza': typeof LabPlazaRouteWithChildren
  '/promotion/lifecycle': typeof PromotionLifecycleRoute
  '/lab/capability/ai-twin': typeof LabCapabilityAiTwinRoute
  '/lab/capability/components': typeof LabCapabilityComponentsRoute
  '/lab/capability/experience': typeof LabCapabilityExperienceRoute
  '/lab/capability/hardware': typeof LabCapabilityHardwareRoute
  '/lab/capability/platforms': typeof LabCapabilityPlatformsRoute
  '/lab/data/datasets': typeof LabDataDatasetsRoute
  '/lab/data/models': typeof LabDataModelsRoute
  '/lab/data/twins': typeof LabDataTwinsRoute
  '/lab/plaza/$id': typeof LabPlazaIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/atlas/demands': typeof AtlasDemandsRoute
  '/atlas/overview': typeof AtlasOverviewRoute
  '/demo/online': typeof DemoOnlineRoute
  '/lab/plaza': typeof LabPlazaRouteWithChildren
  '/promotion/lifecycle': typeof PromotionLifecycleRoute
  '/lab/capability/ai-twin': typeof LabCapabilityAiTwinRoute
  '/lab/capability/components': typeof LabCapabilityComponentsRoute
  '/lab/capability/experience': typeof LabCapabilityExperienceRoute
  '/lab/capability/hardware': typeof LabCapabilityHardwareRoute
  '/lab/capability/platforms': typeof LabCapabilityPlatformsRoute
  '/lab/data/datasets': typeof LabDataDatasetsRoute
  '/lab/data/models': typeof LabDataModelsRoute
  '/lab/data/twins': typeof LabDataTwinsRoute
  '/lab/plaza/$id': typeof LabPlazaIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/atlas/demands'
    | '/atlas/overview'
    | '/demo/online'
    | '/lab/plaza'
    | '/promotion/lifecycle'
    | '/lab/capability/ai-twin'
    | '/lab/capability/components'
    | '/lab/capability/experience'
    | '/lab/capability/hardware'
    | '/lab/capability/platforms'
    | '/lab/data/datasets'
    | '/lab/data/models'
    | '/lab/data/twins'
    | '/lab/plaza/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/atlas/demands'
    | '/atlas/overview'
    | '/demo/online'
    | '/lab/plaza'
    | '/promotion/lifecycle'
    | '/lab/capability/ai-twin'
    | '/lab/capability/components'
    | '/lab/capability/experience'
    | '/lab/capability/hardware'
    | '/lab/capability/platforms'
    | '/lab/data/datasets'
    | '/lab/data/models'
    | '/lab/data/twins'
    | '/lab/plaza/$id'
  id:
    | '__root__'
    | '/'
    | '/atlas/demands'
    | '/atlas/overview'
    | '/demo/online'
    | '/lab/plaza'
    | '/promotion/lifecycle'
    | '/lab/capability/ai-twin'
    | '/lab/capability/components'
    | '/lab/capability/experience'
    | '/lab/capability/hardware'
    | '/lab/capability/platforms'
    | '/lab/data/datasets'
    | '/lab/data/models'
    | '/lab/data/twins'
    | '/lab/plaza/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AtlasDemandsRoute: typeof AtlasDemandsRoute
  AtlasOverviewRoute: typeof AtlasOverviewRoute
  DemoOnlineRoute: typeof DemoOnlineRoute
  LabPlazaRoute: typeof LabPlazaRouteWithChildren
  PromotionLifecycleRoute: typeof PromotionLifecycleRoute
  LabCapabilityAiTwinRoute: typeof LabCapabilityAiTwinRoute
  LabCapabilityComponentsRoute: typeof LabCapabilityComponentsRoute
  LabCapabilityExperienceRoute: typeof LabCapabilityExperienceRoute
  LabCapabilityHardwareRoute: typeof LabCapabilityHardwareRoute
  LabCapabilityPlatformsRoute: typeof LabCapabilityPlatformsRoute
  LabDataDatasetsRoute: typeof LabDataDatasetsRoute
  LabDataModelsRoute: typeof LabDataModelsRoute
  LabDataTwinsRoute: typeof LabDataTwinsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promotion/lifecycle': {
      id: '/promotion/lifecycle'
      path: '/promotion/lifecycle'
      fullPath: '/promotion/lifecycle'
      preLoaderRoute: typeof PromotionLifecycleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/plaza': {
      id: '/lab/plaza'
      path: '/lab/plaza'
      fullPath: '/lab/plaza'
      preLoaderRoute: typeof LabPlazaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/online': {
      id: '/demo/online'
      path: '/demo/online'
      fullPath: '/demo/online'
      preLoaderRoute: typeof DemoOnlineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atlas/overview': {
      id: '/atlas/overview'
      path: '/atlas/overview'
      fullPath: '/atlas/overview'
      preLoaderRoute: typeof AtlasOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atlas/demands': {
      id: '/atlas/demands'
      path: '/atlas/demands'
      fullPath: '/atlas/demands'
      preLoaderRoute: typeof AtlasDemandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/plaza/$id': {
      id: '/lab/plaza/$id'
      path: '/$id'
      fullPath: '/lab/plaza/$id'
      preLoaderRoute: typeof LabPlazaIdRouteImport
      parentRoute: typeof LabPlazaRoute
    }
    '/lab/data/twins': {
      id: '/lab/data/twins'
      path: '/lab/data/twins'
      fullPath: '/lab/data/twins'
      preLoaderRoute: typeof LabDataTwinsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/data/models': {
      id: '/lab/data/models'
      path: '/lab/data/models'
      fullPath: '/lab/data/models'
      preLoaderRoute: typeof LabDataModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/data/datasets': {
      id: '/lab/data/datasets'
      path: '/lab/data/datasets'
      fullPath: '/lab/data/datasets'
      preLoaderRoute: typeof LabDataDatasetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/capability/platforms': {
      id: '/lab/capability/platforms'
      path: '/lab/capability/platforms'
      fullPath: '/lab/capability/platforms'
      preLoaderRoute: typeof LabCapabilityPlatformsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/capability/hardware': {
      id: '/lab/capability/hardware'
      path: '/lab/capability/hardware'
      fullPath: '/lab/capability/hardware'
      preLoaderRoute: typeof LabCapabilityHardwareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/capability/experience': {
      id: '/lab/capability/experience'
      path: '/lab/capability/experience'
      fullPath: '/lab/capability/experience'
      preLoaderRoute: typeof LabCapabilityExperienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/capability/components': {
      id: '/lab/capability/components'
      path: '/lab/capability/components'
      fullPath: '/lab/capability/components'
      preLoaderRoute: typeof LabCapabilityComponentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/capability/ai-twin': {
      id: '/lab/capability/ai-twin'
      path: '/lab/capability/ai-twin'
      fullPath: '/lab/capability/ai-twin'
      preLoaderRoute: typeof LabCapabilityAiTwinRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LabPlazaRouteChildren {
  LabPlazaIdRoute: typeof LabPlazaIdRoute
}

const LabPlazaRouteChildren: LabPlazaRouteChildren = {
  LabPlazaIdRoute: LabPlazaIdRoute,
}

const LabPlazaRouteWithChildren = LabPlazaRoute._addFileChildren(
  LabPlazaRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AtlasDemandsRoute: AtlasDemandsRoute,
  AtlasOverviewRoute: AtlasOverviewRoute,
  DemoOnlineRoute: DemoOnlineRoute,
  LabPlazaRoute: LabPlazaRouteWithChildren,
  PromotionLifecycleRoute: PromotionLifecycleRoute,
  LabCapabilityAiTwinRoute: LabCapabilityAiTwinRoute,
  LabCapabilityComponentsRoute: LabCapabilityComponentsRoute,
  LabCapabilityExperienceRoute: LabCapabilityExperienceRoute,
  LabCapabilityHardwareRoute: LabCapabilityHardwareRoute,
  LabCapabilityPlatformsRoute: LabCapabilityPlatformsRoute,
  LabDataDatasetsRoute: LabDataDatasetsRoute,
  LabDataModelsRoute: LabDataModelsRoute,
  LabDataTwinsRoute: LabDataTwinsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
